### ISSUE TITLE
Cookie banner with Strict Tracking Prevention

### ISSUE THREAD

**Issue by sarah-storm** [stormid/components#162] opened 2021-09-01 09:52 UTC
It's been reported that in some cases, clicking 'accept' on the cookie banner causes the page below to become unresposive to clicks  until the browser is refreshed.

Having tried a few browser/OS combinations, this seems to happen when using FF on MacOS and having your Tracking Protection set to 'Strict'.  Strict settings on FF Windows appear to handle this.    The failure seems to happen silently, with no errors being logged to the console or page.  

It would be good to investigate this further to see at what point the error occurs.  I think it's at the point of the preferences cookie being set, as opposed to any tracking scripts being initiated, as the Cookie does not appear to be listed in the browser until after the refresh that fixes the page.

**Comment by mjbp** [comment] 2021-09-01 21:40
I’ve had a quick look at this and if >1 cookie categories is accepted on many of our recent sites then local links (relative links in the same window) do not work. Opening in a new tab, and links to external URLs are fine. Selecting only one category and everything works fine. I’ve reproduced the same thing locally with a reduced test case using the example code in the cookie banner component on Github - it only breaks local links when loading >1 GTM container.

Tracking protection prevents GTM and Analytics from working by shimming the two libraries. When the shim is in place you can see the sandbox eval code source in the debugger. The file contains the message 
`console.warn("Google Analytics and Tag Manager is being shimmed by Firefox. See https://bugzilla.mozilla.org/show_bug.cgi?id=1713687 for details.”)`

Based on the above I’m inclined to believe that the issue is with Firefox and the shim for analytics and GTM libraries when multiple copies of GTM and analytics are loaded.

If that is correct then a complete fix is out of our hands but we could perhaps detect advanced tracking protection is on (maybe using navigator.doNotTrack === ‘1’?), and not execute the GTM/Analytics loading functions at all if it is.

**Comment by sarah-storm** [comment] 2021-09-02 08:08
An even more narrow set of circumstances!  It all works fine on FireFox PC, so it is possible that it's an issue they'll resolve in a further update of FireFox for Mac.

I'd had a look at the doNotTrack flag, but there are suggestions that this isn't all that accurate for tracking protection and to t[ry and trigger the tracking protection](https://stackoverflow.com/questions/33959324/how-to-detect-if-a-user-is-using-tracking-protection-in-firefox-42) to detect it.  Which doesn't feel like a great solution, although may be the only option to detect the feature that's causing the issue.   I think selecting only the 'do not track' option in FF still allows the scripts to run.

**Comment by mjbp** [comment] 2021-09-02 08:49
I agree that doNotTrack doesn't look reliable. Since it only affects Mac we'd probably need a combination of feature detection and user agent sniffing, adding a chunk of code and points of failure.

Since there are warnings in Firefox about tracking prevention breaking stuff and how to fix it (turning it off), I wonder if the fix is worse than problem.

**Comment by mjbp** [comment] 2021-09-06 16:11
Closing this because the bug is caused by an issue with the way FF/Mac shims Google Tag Manager when there are multiple instances of the GTM, it's not related to any code in the cookie banner library itself.

**Closed by mjbp** 2021-09-06 16:11 UTC
