### ISSUE TITLE
Toggle - CloseOnBlur doesn't always work with Voiceover or Talkback

### ISSUE THREAD

**Issue by sarah-storm** [stormid/components#204] opened 2022-03-15 14:56 UTC
Hi!

Not sure if this is a component or patterns ticket - a bit of both really!

I was doing a bit of AX testing today on a project that's directly using the ExclusiveToggles pattern and noticed it was a little confusing in iOS voiceover.

This pattern uses CloseOnBlur set to true on the toggle component to switch between the search/nav overlays.  iOS does not trigger focus/blur events on items from swipe alone - the user has to activate another item with a press before they trigger.

Therefore, if you open the search box - swipe through it and it closes visually, it's still possible to swipe back to it as the full blur function hasn't properly run.   This also happens with a single toggle, if you swipe through without clicking on another item, or toggling the menu closed.

I've attached a couple of videos to try and explain more clearly... not sure if they do though!  

https://user-images.githubusercontent.com/62299569/158405401-40d16905-8d91-481b-a084-8ca4d6571cb4.MP4

https://user-images.githubusercontent.com/62299569/158405409-bc1f899d-ca17-4b5c-bd1e-758a1577d05b.MP4

Solving this could be difficult without proper running of the focus/blur events.  Should they perhaps have manual triggers only in this pattern?  Or would these cases be pretty infrequent?

**Comment by mjbp** [comment] 2022-03-15 15:45
I'd be keen to bottom-out whether we absolutely can't do this, and whether this behaviour is an iOS Voiceover bug that will be fixed in the future or not. If it's not a bug and we can't fix it, then our current preferred pattern for modal navigation is off the table - we need closeOnBlur to support a full screen navigation design that doesn't trap tab/is a real modal dialog, and closes when focus leaves the nav.

The closeOnBlur option (despite its name), is based on listening for the focusin event at a document level - it may be the case that another event is fired  that we can listen for at some level?

**Comment by sarah-storm** [comment] 2022-03-16 09:19
Findings so far are that the focus/focusin/focusout/blur events will only fire with VoiceOver when used on < button > elements and not < a > (or other focusable items / items with a tabindex set).

Video 1 with links:

https://user-images.githubusercontent.com/62299569/158555620-b80bacd4-23f3-467f-97b9-ff4533facc20.MP4

Video 2 with buttons:

https://user-images.githubusercontent.com/62299569/158555659-28ac91aa-340a-4217-8939-2396194f7efb.MP4

And then also, in order for the blur event to fire, the user has to swipe to another button.  They can't just swipe to a header or link.  Video below:

https://user-images.githubusercontent.com/62299569/158555953-c40cce19-c870-4e55-813d-09d450891191.MP4


And a couple of links detailing other people seeing the same issues:

https://stackoverflow.com/questions/31006404/accessibility-android-talkback-doesnt-fire-focus-event-on-html-content
https://stackoverflow.com/questions/47315314/android-talkback-not-registering-onfocus-for-web-how-do-i-manipulate-accessibil

No events fire on links apart from 'click, mousedown' when the user double taps the links to open them.  This sort of implies that any UI functionality that changes content availability based on focus alone might be best avoided.   

In this instance the content will still be available, any menus etc will not visually close on these devices based on a swipe.  That's probably expected by a real-world user, but I do think it's the kind of thing that would be flagged by our internal AX reviews.  Hopefully we can get some more input on the modal navigation pattern from the wider team.

**Comment by sarah-storm** [comment] 2022-03-16 09:50
A note on the specific example of the exclusive toggles pattern:

- User swipes to search icon
- User double taps to open search toggle
- User's focus is placed on the search input.  They can swipe past the input and the search button and onto the menu button
- In this set up the closeOnBlur event DOES fire, because the next focusable element in the DOM is the Menu < button > tag and so the search overlay closes.
- Double tap the menu button to open it.  Focus is placed on the close icon/button.
- User can swipe through the menu and off the bottom, but the menu DOES NOT close until it hits another button in the content in < main >.

I think the fact that we can swipe back to the hidden search overlay might be a seperate, but related issue

**Comment by sarah-storm** [comment] 2022-04-12 10:21
Adding a bit of a survey result here on a few sites that are considered to have high AX standards:

https://www.scope.org.uk/

- Has burger menu. 
- Opens as takeover
- Swiping through, menu remains open and goes to page underneith.
- Behaves the same way on desktop with keyboard navigation  


https://sse.co.uk/energy

- Has burger menu. 
- Opens as takeover
- Swiping through, menu remains open and goes to page underneith.  
- Behaves the same way on desktop with keyboard navigation


https://www.applevis.com/

- Has dropdown menu
- Menu pushes down page content when opened
- Menu does not loop, but carries on down the page on swipe
- Behaves the same way on desktop with keyboard navigation


https://www.bbc.co.uk/

- Has dropdown menu
- Menu pushes down page content when opened
- Menu does not loop, but carries on down the page on swipe
- Behaves the same way on desktop with keyboard navigation


https://www.bbc.co.uk/news
- Has burger menu. 
- Opens as takeover
- Does not go to page content when swiping off the menu.  Page content cannot be accessed
- No looping behaviour, user swipes back up to close menu
- Behaves the same way on desktop with keyboard navigation


https://www.gov.uk/

- Has dropdown menu
- Menu pushes down page content when opened
- Menu does not loop, but carries on down the page on swipe
- Behaves the same way on desktop with keyboard navigation


https://www.barclays.co.uk/

- Has burger menu. 
- Opens as takeover
- Does not go to page content when swiping off the menu.  Page content cannot be accessed
- No looping behaviour, user swipes back up to close menu
- Behaves the same way on desktop with keyboard navigation


https://www.davidmacd.com/

- Has dropdown menu
- Menu pushes down page content when opened
- Menu does not loop, but carries on down the page on swipe
- Behaves the same way on desktop with keyboard navigation


https://www.tpgi.com/

- Has burger menu. 
- Opens as slideout panel from the right
- When reaching the end of the menu the user begins swiping through the page content.  No looping behaviour or option to close
- Menu does not close on swipe, it remains visible open.  This behaviour is different on desktop/keyboard.  Tabbing out of the menu closes it and user continues on page.


https://www.deque.com/

- Has dropdown menu
- Menu pushes down page content when opened
- Menu does not loop, but carries on down the page on swipe
- Behaves the same way on desktop with keyboard navigation


https://www.nomensa.com/

- Has dropdown menu
- Menu pushes down page content when opened
- Menu does not loop, but carries on down the page on swipe
- Behaves the same way on desktop with keyboard navigation

**Comment by sarah-storm** [comment] 2022-04-12 10:23
They seem to sit in one of three camps:

- Menu behaves the same way as ours, and suffers from the same V/O issue
- Menu is a takeover, but does not attempt to close on blur or loop the user back to the close button.  The page content is not reachable while the menu is open
- The menu does not use the takeover design and pushes content down instead.

**Comment by sarah-storm** [comment] 2022-04-19 14:12
Update:

AX Android Testing is will be done tomorrow which uses the Toggle Callback function to set aria-hidden on all non-header content in the style of 2 above.  Another option being tested is to try the use of CSS as per the BBC site.  Previously this hadn't been enough on its own but should be re-tested now with the latest VO update.

Depending on the outcome of this testing we might want to look at the ui pattern for the non-modal-modal navigation that is currently open for testing (See UI Patterns issue 19 and Slack channel)

A branch has been created for review on the patterns library, which suggests changing our default pattern of menu to number 3. above.

**Comment by sarah-storm** [comment] 2022-04-26 10:01
A version of a toggle-overlay menu with a call back adding aria-hidden to other page elements passed AX testing on devices (with the acknowledgement that manually scrolling back to the close button wasn't ideal).

This resolved the bug with the focus dropping to the page underneath, so could be a good option if the overlay menu is a requirement.

**Comment by mjbp** [comment] 2022-08-25 10:01
A version of the full screen toggle-based menu using the BBC-style CSS only approach (display: none, visibility: hidden on everything other than the nav) has passed ax testing on two of our recent sites.

I think that both the CSS and the aria-hidden approaches are viable options.

I personally favour the CSS approach because in situations where we need an inline always-visible nav on larger screens and off-canvas -> full screen nav on small screens - we don't need to worry about cleaning up aria-hidden markup if the screen resolution changes from small to large.

**Comment by mjbp** [comment] 2022-08-31 09:44
I've changed the implementation of the exclusive toggles pattern (still to be deployed to Netlify) to use the toggle.open custom events rather than closeOnBlur.

I think we need to add some guidance for closeOnBlur in this repo about the limitations discussed here.

**Comment by sarah-storm** [comment] 2022-09-06 08:23
Updated readme with a short dev note - https://github.com/stormid/components/pull/225  Does this sound OK?

**Comment by mjbp** [comment] 2022-09-06 08:34
Closing this with the pattern library and readme updates 🎉
Thanks @sarah-storm.

**Closed by mjbp** 2022-09-06 08:34 UTC
Labels: bug, question
